name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: armadovich/examen-front:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Render CLI
        run: |
          curl -fsSL https://github.com/render/render-cli/releases/latest/download/render-linux-amd64 -o render
          chmod +x render
          sudo mv render /usr/local/bin/

      - name: Verificar instalación de Render CLI
        run: render --version

      - name: Desplegar a Render
        run: render deploy --api-key ${{ secrets.RENDER_API_KEY }} --service-id ${{ secrets.RENDER_SERVICE_ID }}

