name: Build and Deploy to Render

on:
  push:
    branches:
      - main  # Se ejecuta cuando se hace push a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ vars.DOCKERUSERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKERUSERNAME }}/examen-front:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ vars.DOCKERUSERNAME }}/examen-front:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render via API
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'

