name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: armadovich/examen-front:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Render CLI
        run: |
          wget -qO - https://www.get.render.com | sh
          mkdir -p ~/.config/render/bin
          mv ~/.render/bin/render ~/.config/render/bin/render
          chmod +x ~/.config/render/bin/render

      - name: Deploy to Render
        run: |
          ~/.config/render/bin/render login --api-key ${{ secrets.RENDER_API_KEY }}
          ~/.config/render/bin/render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }}
