name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: armadovich/examen-front:latest

  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Install Render CLI
        run: curl -fsSL https://render.com/install | bash
  
      - name: Deploy to Render using Docker Image
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: render deploy --service YOUR_RENDER_SERVICE_ID --image armadovich/examen-front:latest --wait
