name: Build and Deploy to Render

on:
  push:
    branches:
      - main  # Se ejecuta cuando se hace push a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ vars.DOCKERUSERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKERUSERNAME }}/examen-front:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ vars.DOCKERUSERNAME }}/examen-front:latest

  deploy:
    needs: build-and-push  # Espera a que termine el job anterior
    runs-on: ubuntu-latest

    steps:
      - name: Install Render CLI
        run: npm install -g render-cli@latest

      - name: Verify Render CLI Installation
        run: render --version

      - name: Deploy to Render
        run: render deploy --service ${{ secrets.RENDER_SERVICE_ID }} --image ${{ vars.DOCKERUSERNAME }}/examen-front:latest --wait
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
