name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: armadovich/examen-front:latest

  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
  

      - name: Log in to Artifactory
        run: |
          echo ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_API_KEY }} | docker login calculadoraarmada.jfrog.io -u ${{ secrets.JFROG_USER }} --password-stdin
  

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-


      - name: Build Docker image
        run: |
          docker build -t calculadoraarmada.jfrog.io/docker-local/my-app:${{ github.sha }} .

      - name: Push Docker image to Artifactory
        run: |
          docker push calculadoraarmada.jfrog.io/docker-local/my-app:${{ github.sha }}

